### ISSUE TITLE
Config File Update Suggestion

### ISSUE THREAD

**Issue by DuongVanKhoa0811** [SamWilso/SAFE_Official#5]
In the configuration file located at SAFE_Official/configs/VOC-Detection/faster-rcnn/vanilla.yaml, I think you should modify the value on the 4th line to: 'WEIGHTS: ./data/VOC-Detection/faster-rcnn/vanilla/model_final.pth'

Additionally, if you have time, it would be beneficial to review the repository on GitHub for any unintentional errors. This review could help other researchers reproduce results more smoothly.

Best regards
Khoa

**Comment by SamWilso** [comment]
Hi, this one took a while to replicate on my machine. The issue was some linking left over from the VOS repository looking for a folder that did not exist. It did however exist on my machine (outside of the cloned repository), hence why it was never found. 

I've updated `core/__init__.py` to use relative linking and confirmed it works as expected. 

Unfortunately, my availability to work on this repository is limited; I am no longer in academia and have additional family concerns. I am happy to review and continue supporting to the best of my abilities, but my bandwidth to do thorough reviews for a repository which has remained largely inactive for nearly 1 year is rather limited. 

If you experience any other issues, please do not hesitate to open another issue and I will try to fix as soon as possible.
